---
name: Bump package version

'on':
  pull_request:
    types: [labeled]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  bump-version:
    name: Bump package version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Bump version
        if: startsWith(github.event.label.name, 'release:')
        env:
          LABEL_NAME: ${{ github.event.label.name }}
        run: npm --no-git-tag-version version "${LABEL_NAME##release:}"
      - name: Push changes
        run: |
          git config --local user.name '${{ github.actor }}'
          git config --local user.email '${{ github.actor }}@users.noreply.github.com'
          git add --all package.json package-lock.json
          git commit -m 'Bump package version' || exit 0
          git push
