---
name: CD

'on':
  push:
    branches: [master]
    tags: [v*]
  workflow_dispatch:

concurrency:
  group: cd/${{ github.repo }}/${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Create new release
        uses: drugscom/release-action@v1
        with:
          update-major-tag: true
